USE [master]
GO

/****** Object:  Database [UniversityDb]    Script Date: 1/6/2021 6:31:47 ******/
CREATE DATABASE [UniversityDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UniversityDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UniversityDb.mdf' , SIZE = 40960KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UniversityDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UniversityDb_log.ldf' , SIZE = 20480KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UniversityDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UniversityDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UniversityDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UniversityDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UniversityDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UniversityDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [UniversityDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UniversityDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UniversityDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UniversityDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UniversityDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UniversityDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UniversityDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UniversityDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UniversityDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UniversityDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UniversityDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UniversityDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UniversityDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UniversityDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UniversityDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UniversityDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UniversityDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UniversityDb] SET RECOVERY FULL 
GO

ALTER DATABASE [UniversityDb] SET  MULTI_USER 
GO

ALTER DATABASE [UniversityDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UniversityDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UniversityDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UniversityDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UniversityDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UniversityDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UniversityDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UniversityDb] SET  READ_WRITE 
GO


